[package]
name = "SavedTodo"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
toml = "0.8.22"
serde = { version = "1.0.219", features = ["derive"] }
ratatui = {version = "0.29.0", features = ["all-widgets"]}
color-eyre = "0.6.0"
unicode-width = "0.2.0"
